select 'field type' as '';
INSERT INTO Survey_Field_Type (field_type) VALUES ('TextBox');
INSERT INTO Survey_Field_Type (field_type) VALUES ('Email');
INSERT INTO Survey_Field_Type (field_type) VALUES ('Checkbox');
INSERT INTO Survey_Field_Type (field_type) VALUES ('List');
INSERT INTO Survey_Field_Type (field_type) VALUES ('Button');
INSERT INTO Survey_Field_Type (field_type) VALUES ('DatePicker');
INSERT INTO Survey_Field_Type (field_type) VALUES ('DropdownList');
INSERT INTO Survey_Field_Type (field_type) VALUES ('RadioButton');
INSERT INTO Survey_Field_Type (field_type) VALUES ('GroupBox');
INSERT INTO Survey_Field_Type (field_type) VALUES ('Slider');
INSERT INTO Survey_Field_Type (field_type) VALUES ('Matrix');