//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicSurvey.Server.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.survey = new HashSet<survey>();
        }
    
        public decimal id { get; set; }
        public string name { get; set; }
        public decimal city_id { get; set; }
        public string address { get; set; }
        public string phone_number { get; set; }
        public string postal_code { get; set; }
    
        public virtual city city { get; set; }
        public virtual ICollection<survey> survey { get; set; }
    }
}
