//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicSurvey.Server.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
	using System.Diagnostics;
    
    public partial class DbSurveysContext : DbContext
    {
        public DbSurveysContext()
            : base("name=DbSurveysContext")
        {
			Database.Log = m => Trace.WriteLine(m);

        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<city> city { get; set; }
        public DbSet<company> company { get; set; }
        public DbSet<country> country { get; set; }
        public DbSet<survey> survey { get; set; }
        public DbSet<survey_detail> survey_detail { get; set; }
        public DbSet<survey_field> survey_field { get; set; }
        public DbSet<survey_field_type> survey_field_type { get; set; }
        public DbSet<survey_field_vocabulary_cross> survey_field_vocabulary_cross { get; set; }
        public DbSet<survey_page> survey_page { get; set; }
        public DbSet<survey_template> survey_template { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<user_language_cross> user_language_cross { get; set; }
        public DbSet<user_right> user_right { get; set; }
        public DbSet<vocabulary> vocabulary { get; set; }
        public DbSet<user_language> user_language { get; set; }
    }
}
