//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicSurvey.Server.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey_detail
    {
        public decimal id { get; set; }
        public decimal survey_field_id { get; set; }
        public decimal fk_parent_survey_id { get; set; }
        public string user_answer { get; set; }
    
        public virtual survey survey { get; set; }
        public virtual survey_field survey_field { get; set; }
    }
}
