//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicSurvey.Server.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey_field_type
    {
        public survey_field_type()
        {
            this.survey_field = new HashSet<survey_field>();
        }
    
        public decimal id { get; set; }
        public string field_type { get; set; }
    
        public virtual ICollection<survey_field> survey_field { get; set; }
    }
}
