//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicSurvey.Server.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey_field
    {
        public survey_field()
        {
            this.survey_field_template = new HashSet<survey_field_template>();
        }
    
        public decimal id { get; set; }
        public decimal field_type_id { get; set; }
        public decimal default_value_id { get; set; }
    
        public virtual survey_field_type survey_field_type { get; set; }
        public virtual vocabulary vocabulary { get; set; }
        public virtual ICollection<survey_field_template> survey_field_template { get; set; }
    }
}
