//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicSurvey.Server.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey_field_template
    {
        public survey_field_template()
        {
            this.survey_detail = new HashSet<survey_detail>();
        }
    
        public decimal id { get; set; }
        public decimal survey_template_id { get; set; }
        public decimal survey_field_id { get; set; }
        public Nullable<decimal> word_id { get; set; }
    
        public virtual ICollection<survey_detail> survey_detail { get; set; }
        public virtual survey_field survey_field { get; set; }
        public virtual survey_template survey_template { get; set; }
        public virtual vocabulary vocabulary { get; set; }
    }
}
