//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicSurvey.Server.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey_field
    {
        public survey_field()
        {
            this.survey_detail = new HashSet<survey_detail>();
        }
    
        public decimal id { get; set; }
        public decimal fk_parent_survey_id { get; set; }
        public decimal fk_survey_field_type { get; set; }
        public decimal page_index { get; set; }
        public decimal group_index { get; set; }
    
        public virtual ICollection<survey_detail> survey_detail { get; set; }
        public virtual survey_template survey_template { get; set; }
        public virtual survey_field_type survey_field_type { get; set; }
    }
}
