//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicSurvey.Server.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey_detail
    {
        public survey_detail()
        {
            this.survey = new HashSet<survey>();
        }
    
        public decimal id { get; set; }
        public decimal survey_field_template_id { get; set; }
        public string field_value { get; set; }
    
        public virtual ICollection<survey> survey { get; set; }
        public virtual survey_field_template survey_field_template { get; set; }
    }
}
