//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicSurvey.Server.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey_page
    {
        public survey_page()
        {
            this.survey_field = new HashSet<survey_field>();
        }
    
        public decimal id { get; set; }
        public decimal page_index { get; set; }
        public string page_title { get; set; }
        public decimal fk_survey_template_parent_id { get; set; }
    
        public virtual ICollection<survey_field> survey_field { get; set; }
        public virtual survey_template survey_template { get; set; }
    }
}
