//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicSurvey.Server.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.survey = new HashSet<survey>();
            this.survey_template = new HashSet<survey_template>();
            this.user_language = new HashSet<user_language>();
        }
    
        public decimal id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public decimal user_right_id { get; set; }
        public sbyte is_deleted { get; set; }
    
        public virtual ICollection<survey> survey { get; set; }
        public virtual ICollection<survey_template> survey_template { get; set; }
        public virtual user_right user_right { get; set; }
        public virtual ICollection<user_language> user_language { get; set; }
    }
}
